name: Unit Tests CUDA

on:
  push:
    branches: test_ye
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  trigger_unit_test:
    defaults:
      run:
        shell: bash
    runs-on: [self-hosted, ye_test]
    container:
      image: localhost:5000/flagscale-cuda12.8.1-torch2.8.0-python3.10-vllm0.11.0_fl.0.1:20260205
      options: --gpus all --shm-size=500g --hostname flagscale_cicd --user root --ulimit nofile=65535:65535
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Unit Tests via Reusable Workflow
        uses: ./.github/workflows/unit_test.yml